### ISSUE TITLE
Support TS

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/eslint-plugin-doc-code-blocks#1]
Basically I need a way to extract the block comments from TS source. I use https://www.npmjs.com/package/extract-comments for JS, which uses esprima underneath. Not sure about TS though..

**Comment by davewasmer** [comment]
I think the challenge here is that eslint itself doesn't support Typescript (there's an [experimental parser](https://github.com/eslint/typescript-eslint-parser) but it's still unstable). So authors of Typescript projects won't be using eslint at all in the first place (i.e. their lint command in their build step won't be `$ eslint .`).

There is a [tslint](https://github.com/palantir/tslint) project thought - perhaps this plugin could be ported there as well, or refactored into a linter agnostic core with eslint/tslint shims.

**Comment by knownasilya** [comment]
There are two ways to support TS:

1. Process TS file for codeblocks with ```js/```javascript
2. Process TS file for codeblocks with ```ts/```typescript and ```js (since ts should support both)

This plugin could do the first one, but would add an extra dependency for non TS users.

**Comment by knownasilya** [comment]
Will look at reimplementing in tslint if there are requests.
